// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHob2wPA1SpiYGFPJ20Dq7w74_7ZPNUs',
    appId: '1:557037663378:web:0b0c11557d101daa44224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    authDomain: 'fic-shitamichi-project1-376a4.firebaseapp.com',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    measurementId: 'G-GSZQHZS1VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWqNALiUGGOkjq61XuvnvOuZLPh0SDeJQ',
    appId: '1:557037663378:android:0285b5b52ce61bdb44224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZDhJ8AFRMheDpFnZ24DQrG1Tgw1x2Oc',
    appId: '1:557037663378:ios:0a0588927811c28444224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjZDhJ8AFRMheDpFnZ24DQrG1Tgw1x2Oc',
    appId: '1:557037663378:ios:0a0588927811c28444224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtHob2wPA1SpiYGFPJ20Dq7w74_7ZPNUs',
    appId: '1:557037663378:web:287ce3f413d1cce644224b',
    messagingSenderId: '557037663378',
    projectId: 'fic-shitamichi-project1-376a4',
    authDomain: 'fic-shitamichi-project1-376a4.firebaseapp.com',
    storageBucket: 'fic-shitamichi-project1-376a4.appspot.com',
    measurementId: 'G-42NRPGV2H7',
  );
}
